"""initial schema

Revision ID: 1c587c569525
Revises:
Create Date: 2026-05-03 01:06:13.880826
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1c587c569525'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('api_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_token'), 'users', ['api_token'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('policy_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_documents_file_hash'), 'policy_documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_policy_documents_status'), 'policy_documents', ['status'], unique=False)
    op.create_index(op.f('ix_policy_documents_user_id'), 'policy_documents', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('pinecone_vector_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_document_id'], ['policy_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_document_id', 'chunk_index', name='uq_document_chunk_index')
    )
    op.create_index(op.f('ix_document_chunks_pinecone_vector_id'), 'document_chunks', ['pinecone_vector_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_policy_document_id'), 'document_chunks', ['policy_document_id'], unique=False)
    op.create_table('policy_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('policy_document_id', sa.Integer(), nullable=True),
    sa.Column('policy_type', sa.String(length=255), nullable=False),
    sa.Column('coverage', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('risk', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_analysis', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('final_output_payload', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_document_id'], ['policy_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_analyses_policy_document_id'), 'policy_analyses', ['policy_document_id'], unique=False)
    op.create_index(op.f('ix_policy_analyses_status'), 'policy_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_policy_analyses_user_id'), 'policy_analyses', ['user_id'], unique=False)
    op.create_table('analysis_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_analysis_id', sa.Integer(), nullable=False),
    sa.Column('document_chunk_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['policy_analysis_id'], ['policy_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_sources_document_chunk_id'), 'analysis_sources', ['document_chunk_id'], unique=False)
    op.create_index(op.f('ix_analysis_sources_policy_analysis_id'), 'analysis_sources', ['policy_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_sources_policy_analysis_id'), table_name='analysis_sources')
    op.drop_index(op.f('ix_analysis_sources_document_chunk_id'), table_name='analysis_sources')
    op.drop_table('analysis_sources')
    op.drop_index(op.f('ix_policy_analyses_user_id'), table_name='policy_analyses')
    op.drop_index(op.f('ix_policy_analyses_status'), table_name='policy_analyses')
    op.drop_index(op.f('ix_policy_analyses_policy_document_id'), table_name='policy_analyses')
    op.drop_table('policy_analyses')
    op.drop_index(op.f('ix_document_chunks_policy_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_pinecone_vector_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_policy_documents_user_id'), table_name='policy_documents')
    op.drop_index(op.f('ix_policy_documents_status'), table_name='policy_documents')
    op.drop_index(op.f('ix_policy_documents_file_hash'), table_name='policy_documents')
    op.drop_table('policy_documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_token'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
